name: Pulumi Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pulumi pulumi-aws pulumi_docker

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          source venv/bin/activate
          pulumi login

      - name: Pulumi stack select
        run: |
          source venv/bin/activate
          pulumi stack select Galadon123/temp-dev --cwd infrastructure

      - name: Pulumi refresh
        run: |
          source venv/bin/activate
          pulumi refresh --yes --cwd infrastructure

      - name: Pulumi up
        run: |
          source venv/bin/activate
          pulumi up --yes --cwd infrastructure
